### ISSUE TITLE
Broken english output

### ISSUE THREAD

**Issue by choilive** [squarecat/ellie#14] opened 2023-02-02 00:05 UTC
Tried generating a response with Ellie - this is part of the output I received.

> That said, at this time we don't have any plans to take advantage of sTraek.io or other eiugtolutions dttrelaed to sgaherin data eabo our website aviitors. We are nconfnt with the strategiesnd tactics that are currtly working for us.

Not sure I see the value in a tool that can't generate even intelligible output.

**Comment by Jivings** [comment] 2023-03-08 07:21
Thanks for the report. I think this is a duplicate of [this issue](https://github.com/squarecat/ellie/issues/7).

Can you check if disabling Gmail's grammar/spellcheck fixes it?

**Comment by Jivings** [comment] 2023-03-08 07:28
Actually I think we've fixed this in the latest version of Ellie 👍

**Closed as completed by Jivings** 2023-03-08 07:28 UTC
Labels: bug
